/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneLayout;
import utils.Mensajes;
import utils.SocketHandler;
import utils.UsuarioActual;

/**
 *
 * @author Manuel
 */
public class Carta extends javax.swing.JPanel {

    private Inicio inicio;
    int x = 0;
    int y = 0;

    /**
     * Creates new form Carta
     */
    public Carta(Inicio inicio) {
        this.inicio = inicio;
        initComponents();
        GridBagLayout gl = new java.awt.GridBagLayout();
        jPanelContenedor.setLayout(gl);
        setSize(1000,1800);

        leerCarta();
    }

    public void leerCarta() {
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.fill = GridBagConstraints.VERTICAL;

        jPanelContenedor.removeAll();
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        SocketHandler.getOut().println(Mensajes.PETICION_MOSTRAR_CARTA + "--" + UsuarioActual.getId());
        try {
            String received = SocketHandler.getIn().readLine();
            String[] args = received.split("--");
            int numProductos = Integer.parseInt(args[1]);

            try {
                for (int i = 0; i < numProductos; i++) {
                    constraints.gridx = x;
                    constraints.gridy = y;

                    constraints.gridwidth = 1;

                    constraints.insets = new Insets(5, 5, 5, 5);
                    received = SocketHandler.getIn().readLine();
                    args = received.split("--");
                    String flag = args[0];
                    JPanelProducto producto = new JPanelProducto(this);
                    producto.setId(Integer.parseInt(args[4]));
                    producto.getjLabelNombre().setText(args[1]);
                    producto.getjLabelNombre().setAlignmentX(CENTER_ALIGNMENT);
                    producto.getjLabelIngredientes().setText(args[2]);
                    producto.getjLabelPrecio().setText(args[3]);
                    jPanelContenedor.add(producto, constraints);
                    //jScrollPane1.add(producto, constraints);
                    jPanelContenedor.validate();
                    producto.setVisible(true);
                    producto.setSize(675, 100);
                    jPanelContenedor.repaint();
                    //x++;
                    y++;
                }

            } catch (IOException ex) {
                Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (IOException ex) {
            Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAnadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelContenedor = new javax.swing.JPanel();

        jButtonAnadir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAnadir.setText("Añadir producto");
        jButtonAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirActionPerformed(evt);
            }
        });

        jPanelContenedor.setLayout(new java.awt.GridBagLayout());
        jScrollPane1.setViewportView(jPanelContenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(jButtonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirActionPerformed
        AnadirProducto ap = new AnadirProducto(this);
        ap.setVisible(true);
    }//GEN-LAST:event_jButtonAnadirActionPerformed

    /* public JPanel getjPanelContenedor() {
        return jPanelContenedor;
    }

    public void setjPanelContenedor(JPanel jPanelContenedor) {
        this.jPanelContenedor = jPanelContenedor;
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnadir;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
