/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import utils.Mensajes;
import utils.SocketHandler;
import utils.UsuarioActual;

/**
 *
 * @author Manuel
 */
public class DetallesPedido extends javax.swing.JPanel {

    private int idPedido;
    private Pedidos pedidos;
    private String estado;
    ArrayList<String> estados = new ArrayList<>();

    /**
     * Creates new form DetallesPedido
     */
    public DetallesPedido(int idPedido, Pedidos pedidos) {
        this.pedidos = pedidos;
        this.idPedido = idPedido;
        initComponents();
        jTextAreaProductos.setEditable(false);
        rellenarPedido();
        if (!jLabelRepartidor.getText().equals("Repartidor: ")) {
            jButtonRepartidor.setEnabled(false);
        }
    }

    public void rellenarPedido() {
        try {
            SocketHandler.getOut().println(Mensajes.PETICION_MOSTRAR_DETALLESPEDIDO + "--" + idPedido);

            String received = SocketHandler.getIn().readLine();
            String[] args = received.split("--");
            jLabelDireccion.setText("Dirección: " + args[1]);
            jLabelFecha.setText("Fecha pedido: " + args[3]);
            jLabelNombre.setText("Nombre cliente: " + args[2]);
            jLabelPrecioTotal.setText("Precio total: " + args[4] + "€");
            if (!args[5].equals("0")) {
                jLabelRepartidor.setText("Repartidor: " + args[5]);
            } else {
                jLabelRepartidor.setText("Repartidor: ");
            }

            estado = args[6];

            int numPedidos = Integer.parseInt(args[9]);
            for (int i = 0; i < numPedidos; i++) {
                received = SocketHandler.getIn().readLine();
                args = received.split("--");
                jTextAreaProductos.setText(jTextAreaProductos.getText() + "Producto: " + args[1] + " - Precio: " + args[3] + "\n");
            }

            SocketHandler.getOut().println(Mensajes.PETICION_OBTENER_ESTADOS);

            received = SocketHandler.getIn().readLine();
            args = received.split("--");
            String flag = args[0];

            if (flag.equals(Mensajes.PETICION_OBTENER_ESTADOS_CORRECTO)) {
                int numCategorias = Integer.parseInt(args[1]);
                for (int i = 0; i < numCategorias; i++) {
                    received = SocketHandler.getIn().readLine();
                    args = received.split("--");
                    estados.add(args[1]);
                }

                jComboBoxEstado.setModel(new DefaultComboBoxModel(estados.toArray()));
                for (int i = 0; i < jComboBoxEstado.getItemCount(); i++) {
                    if (jComboBoxEstado.getItemAt(i).toString().equals(estado)) {
                        jComboBoxEstado.setSelectedIndex(i);
                        break;
                    }
                }
                int posicion = jComboBoxEstado.getSelectedIndex();
                for (int i = 0; i < posicion; i++) {
                    jComboBoxEstado.removeItemAt(0);
                }
            }

        } catch (IOException ex) {
            Logger.getLogger(DetallesPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public JLabel getjLabelRepartidor() {
        return jLabelRepartidor;
    }

    public void setjLabelRepartidor(JLabel jLabelRepartidor) {
        this.jLabelRepartidor = jLabelRepartidor;
    }

    public int getIdPedido() {
        return idPedido;
    }

    public void setIdPedido(int idPedido) {
        this.idPedido = idPedido;
    }

    public JButton getjButtonRepartidor() {
        return jButtonRepartidor;
    }

    public void setjButtonRepartidor(JButton jButtonRepartidor) {
        this.jButtonRepartidor = jButtonRepartidor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jLabelPrecioTotal = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaProductos = new javax.swing.JTextArea();
        jLabelProductos = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelRepartidor = new javax.swing.JLabel();
        jButtonRepartidor = new javax.swing.JButton();
        jLabelEstado = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox<>();
        jButtonEstado = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 600));

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre");

        jLabelPrecioTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPrecioTotal.setText("Precio total: ");

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelFecha.setText("Fecha");

        jTextAreaProductos.setBackground(new java.awt.Color(240, 240, 240));
        jTextAreaProductos.setColumns(20);
        jTextAreaProductos.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jTextAreaProductos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaProductos);

        jLabelProductos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelProductos.setText("Productos");

        jLabelDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDireccion.setText("Dirección");

        jLabelRepartidor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRepartidor.setText("Repartidor");

        jButtonRepartidor.setText("Seleccionar");
        jButtonRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepartidorActionPerformed(evt);
            }
        });

        jLabelEstado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEstado.setText("Estado");

        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });

        jButtonEstado.setText("Enviar");
        jButtonEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabelRepartidor, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonRepartidor, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(jButtonEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabelProductos))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jLabelPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonRepartidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRepartidor, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEstado))
                .addGap(24, 24, 24)
                .addComponent(jLabelProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepartidorActionPerformed
        SeleccionarRepartidor sr = new SeleccionarRepartidor(this);
        sr.setVisible(true);

    }//GEN-LAST:event_jButtonRepartidorActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jButtonEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstadoActionPerformed
        int posicion = jComboBoxEstado.getSelectedIndex() + 1;
        int posItem = estados.indexOf(jComboBoxEstado.getSelectedItem()) + 1;
        SocketHandler.getOut().println(Mensajes.PETICION_ACTUALIZAR_ESTADO + "--" + idPedido + "--" + posItem);
        for (int i = 0; i < posicion - 1; i++) {
            jComboBoxEstado.removeItemAt(0);
        }

    }//GEN-LAST:event_jButtonEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEstado;
    private javax.swing.JButton jButtonRepartidor;
    private javax.swing.JComboBox<String> jComboBoxEstado;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecioTotal;
    private javax.swing.JLabel jLabelProductos;
    private javax.swing.JLabel jLabelRepartidor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaProductos;
    // End of variables declaration//GEN-END:variables
}
