/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import utils.Mensajes;
import utils.SocketHandler;

/**
 *
 * @author Manuel
 */
public class JPanelValoracion extends javax.swing.JPanel {

    private Valoraciones valoraciones;
    private int idValoracion;

    /**
     * Creates new form JPanelProducto
     */
    public JPanelValoracion(Valoraciones valoraciones) {
        this.valoraciones = valoraciones;
        initComponents();
        jTextAreaComentario.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaComentario = new javax.swing.JTextArea();
        jLabelPuntuacion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextAreaComentario.setBackground(new java.awt.Color(153, 204, 255));
        jTextAreaComentario.setColumns(20);
        jTextAreaComentario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextAreaComentario.setRows(5);
        jScrollPane1.setViewportView(jTextAreaComentario);

        jLabelPuntuacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPuntuacion.setText("Puntuación: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelPuntuacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    public Valoraciones getValoraciones() {
        return valoraciones;
    }

    public void setValoraciones(Valoraciones valoraciones) {
        this.valoraciones = valoraciones;
    }

    public int getIdValoracion() {
        return idValoracion;
    }

    public void setIdValoracion(int idValoracion) {
        this.idValoracion = idValoracion;
    }

    public JLabel getjLabelPuntuacion() {
        return jLabelPuntuacion;
    }

    public void setjLabelPuntuacion(JLabel jLabelPuntuacion) {
        this.jLabelPuntuacion = jLabelPuntuacion;
    }

    public JTextArea getjTextAreaComentario() {
        return jTextAreaComentario;
    }

    public void setjTextAreaComentario(JTextArea jTextAreaComentario) {
        this.jTextAreaComentario = jTextAreaComentario;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelPuntuacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaComentario;
    // End of variables declaration//GEN-END:variables
}
