  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextPane;
import utils.Mensajes;
import utils.SocketHandler;

/**
 *
 * @author Manuel
 */
public class JPanelPedido extends javax.swing.JPanel {

    private Pedidos pedidos;
    private int id;

    /**
     * Creates new form JPanelProducto
     */
    public JPanelPedido(Pedidos pedidos) {
        this.pedidos=pedidos;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFecha = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelFecha.setText("Fecha: ");

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelPrecio.setText("Total: 0,0€");

        jLabelDireccion.setBackground(new java.awt.Color(153, 204, 255));
        jLabelDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDireccion.setText("Dirección: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (!pedidos.getRecargarPedidos().isInterrupted()) {
            pedidos.getRecargarPedidos().interrupt();
        }
        pedidos.getjPanelContenedor().removeAll();
        DetallesPedido dp = new DetallesPedido(id, pedidos);
        pedidos.getjPanelContenedor().add(dp);
        pedidos.getjPanelContenedor().validate();
        dp.setSize(1000,1800);
        pedidos.getjPanelContenedor().setSize(1000,1800);
        dp.setVisible(true);
        pedidos.getjPanelContenedor().repaint();
        pedidos.getRecargarPedidos().setRecargar(false);
    }//GEN-LAST:event_formMouseClicked

    public Pedidos getPedidos() {
        return pedidos;
    }

    public void setPedidos(Pedidos pedidos) {
        this.pedidos = pedidos;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public JLabel getjLabelDireccion() {
        return jLabelDireccion;
    }

    public void setjLabelDireccion(JLabel jLabelDireccion) {
        this.jLabelDireccion = jLabelDireccion;
    }

    public JLabel getjLabelFecha() {
        return jLabelFecha;
    }

    public void setjLabelFecha(JLabel jLabelFecha) {
        this.jLabelFecha = jLabelFecha;
    }

    public JLabel getjLabelPrecio() {
        return jLabelPrecio;
    }

    public void setjLabelPrecio(JLabel jLabelPrecio) {
        this.jLabelPrecio = jLabelPrecio;
    }

   

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelPrecio;
    // End of variables declaration//GEN-END:variables
}
