/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import utils.UsuarioActual;

/**
 *
 * @author Manuel
 */
public class Perfil extends javax.swing.JPanel {

    private Inicio inicio;
    private Administrador admin;

    /**
     * Creates new form Perfil
     *
     * @param inicio
     */
    public Perfil(Inicio inicio) {
        this.inicio = inicio;
        initComponents();
        rellenarCampos();
    }

    public Perfil(Administrador a) {
        this.admin = a;
        initComponents();
        rellenarCampos();
    }

    public void rellenarCampos() {
        jLabelNombre.setText(jLabelNombre.getText() + UsuarioActual.getNombre());
        jLabelUsuario.setText(jLabelUsuario.getText() + UsuarioActual.getUsuario());
        jLabelEmail.setText(jLabelEmail.getText() + UsuarioActual.getEmail());
        jLabelTelefono.setText(jLabelTelefono.getText() + UsuarioActual.getTelefono());
        jLabelDireccion.setText(jLabelDireccion.getText() + UsuarioActual.getDireccion());
    }

    public void setInicio(Inicio inicio) {
        this.inicio = inicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUsuario = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUsuario.setText("Usuario: ");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre: ");

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEmail.setText("Email: ");

        jLabelDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDireccion.setText("Dirección: ");

        jLabelTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTelefono.setText("Teléfono: ");

        jButtonModificar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonModificar.setText("Modificar perfil");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCerrarSesion.setText("Cerrar sesión");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDireccion)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelUsuario)
                            .addComponent(jLabelTelefono)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(275, 275, 275))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabelNombre)
                .addGap(18, 18, 18)
                .addComponent(jLabelUsuario)
                .addGap(18, 18, 18)
                .addComponent(jLabelEmail)
                .addGap(18, 18, 18)
                .addComponent(jLabelTelefono)
                .addGap(18, 18, 18)
                .addComponent(jLabelDireccion)
                .addGap(42, 42, 42)
                .addComponent(jButtonModificar)
                .addGap(18, 18, 18)
                .addComponent(jButtonCerrarSesion)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed

        ModificarPerfil modificarPerfil = new ModificarPerfil();

        if (inicio != null) {
            inicio.getjPanelContenedor().add(modificarPerfil);
            inicio.getjPanelContenedor().validate();
            modificarPerfil.setSize(675, 482);
            this.setVisible(false);
            modificarPerfil.setVisible(true);
            inicio.getjPanelContenedor().repaint();
        }else{
            modificarPerfil.getjTextFieldUsuario().setEditable(false);
            modificarPerfil.getjTextFieldNombre().setEditable(false);
            modificarPerfil.getjTextFieldDireccion().setEditable(false);
            admin.getjPanelContenedor().add(modificarPerfil);
            admin.getjPanelContenedor().validate();
            modificarPerfil.setSize(675, 482);
            this.setVisible(false);
            modificarPerfil.setVisible(true);
            admin.getjPanelContenedor().repaint();
        }

    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        VentanaPrincipal vp = new VentanaPrincipal();
        vp.setVisible(true);
        if (inicio != null)
            inicio.dispose();    
        else
            admin.dispose();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelUsuario;
    // End of variables declaration//GEN-END:variables
}
